POST https://localhost:5000/carrinhos
Content-Type: application/json
Authorization: Bearer {{localStorage.getItem('token')}}

{
  "idUsuario": "678f1b424c674ad9f2dda623",
  "jogo": [
    {
      "jogoid": "teste"
    }
  ]
}
